#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xwininfo
Version  : 1.1.6
Release  : 7
URL      : https://www.x.org/releases/individual/app/xwininfo-1.1.6.tar.gz
Source0  : https://www.x.org/releases/individual/app/xwininfo-1.1.6.tar.gz
Source1  : https://www.x.org/releases/individual/app/xwininfo-1.1.6.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: xwininfo-bin = %{version}-%{release}
Requires: xwininfo-license = %{version}-%{release}
Requires: xwininfo-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-shape)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
xwininfo prints information about windows on an X server.
Various information is displayed depending on which options are selected.

%package bin
Summary: bin components for the xwininfo package.
Group: Binaries
Requires: xwininfo-license = %{version}-%{release}

%description bin
bin components for the xwininfo package.


%package license
Summary: license components for the xwininfo package.
Group: Default

%description license
license components for the xwininfo package.


%package man
Summary: man components for the xwininfo package.
Group: Default

%description man
man components for the xwininfo package.


%prep
%setup -q -n xwininfo-1.1.6
cd %{_builddir}/xwininfo-1.1.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1681147491
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1681147491
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xwininfo
cp %{_builddir}/xwininfo-%{version}/COPYING %{buildroot}/usr/share/package-licenses/xwininfo/530c98691d9e3afbd64c7f402002a8df8c42de2b || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xwininfo

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xwininfo/530c98691d9e3afbd64c7f402002a8df8c42de2b

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xwininfo.1
